import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/config/Providers";
import { ProtectedRoutes } from "@/app/hooks/ProtectedRoutes";
import LayoutTheme from "./themes/LayoutTheme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <LayoutTheme>
          <ProtectedRoutes>           
            {children}
          </ProtectedRoutes>
        </LayoutTheme>
      </Providers>
    </html>
  );
}
